# Generated by Django 6.0 on 2025-12-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_reg_web', '0002_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('company', 'project_id')},
        ),
    ]
