# Generated by Django 6.0 on 2026-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_reg_web', '0004_alter_timeregistry_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeregistry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
