# Generated by Django 6.0 on 2026-04-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_reg_web', '0006_company_members_alter_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisie_id', models.IntegerField()),
                ('divisie_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisies', to='time_reg_web.company')),
            ],
            options={
                'unique_together': {('company', 'divisie_id')},
            },
        ),
        migrations.AddField(
            model_name='milstones',
            name='divisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milstones', to='time_reg_web.divisies'),
        ),
        migrations.AddField(
            model_name='timeregistry',
            name='divisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_registrys', to='time_reg_web.divisies'),
        ),
        migrations.AddField(
            model_name='todo',
            name='divisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='time_reg_web.divisies'),
        ),
    ]
