# Generated by Django 6.0 on 2026-06-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_reg_web", "0012_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="APITokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                ("remote_ip", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="time_reg_web.apitoken",
                    ),
                ),
            ],
        ),
    ]
